name: upload

on:
  workflow_run:
    workflows: ["build"]
    types: [completed]
    branches: '**'

jobs:
  upload:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: baz
        run: echo ${{ github.event }}
