name: log

on:
  workflow_run:
    workflows: ["build"]
    types: [completed]
    branches: '**'

jobs:
  upload:
    runs-on: ubuntu-latest
    name: Log
    steps:
      - name: bar
        run: echo ${{ github.repository }}
