name: upload

on:
  workflow_run:
    workflows: [build]
    types: [completed]

jobs:
  upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository == 'raboof/test' }}
    name: Upload
    steps:
      - name: bar
        command: echo bar
