name: 'Sonar Fork Build'
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: 'Build project'
    runs-on: ubuntu-latest
    steps:
      - name: 'Build'
        run: mvn install

      - name: 'Prepare Sonar analysis'
        uses: evaristegalois11/sonar-fork-analysis@v1
